preferred_outputs:
  - HDMI
  - DP
  - DVI
  - VGA
  - TV
preferred_resolutions:
  - 7680x4320
  - 3840x2160
  - 1920x1080
  - 1280x720
  - 720x576
preferred_refreshrates:
  - 50
  - 60

intel_boot_options: ""
intel_set_boot_edid: false
nvidia_force_dpi: ""
