---
# file: roles/yavdr-xorg/tasks/setup-xorg.yml
- name: create directories for systemd drop-in files
  file:
    dest: '{{ item }}'
    state: directory
  loop:
    - "/etc/systemd/system/x@.service.d/"
    - "/etc/systemd/system/vdr.service.d/"
    - "/etc/systemd/system/user@{{ vdr.uid }}.service.d/"
    - "/etc/X11/xorg.conf.d/"

- name: systemd-drop-in | add dependency to X-server for vdr.service
  template:
    src: templates/vdr-xorg.conf
    dest: /etc/systemd/system/vdr.service.d/vdr-xorg.conf

- name: systemd-drop-in | start x@.service after plymouth.service
  template:
    src: templates/x@service.d/plymouth.conf.j2
    dest: /etc/systemd/system/x@.service.d/plymouth.conf

- name: systemd-drop-in | start x@.service before xlogin@.service
  template:
    src: templates/x@service.d/xlogin.conf.j2
    dest: /etc/systemd/system/x@.service.d/xlogin.conf

- name: systemd-drop-in | load environment file for vdr.service
  template:
    src: templates/systemd/vdr-environ.j2
    dest: /etc/systemd/system/vdr.service.d/load-environ.conf

- name: systemd-drop-in | user@{{ vdr.uid }}.service depends on x@vt7.service
  template:
    src: templates/user@666.service.d/x-dependency.conf.j2
    dest: '/etc/systemd/system/user@{{ vdr.uid }}.service.d/x-dependency.conf'

- name: vdr-config | start softhddevice detached and set audio to pulseaudio
  lineinfile:
    path: /etc/vdr/conf.avail/softhddevice.conf
    line: '{{ item }}'
  loop:
      - '-D'
      - '-w alsa-driver-broken'
      # - '-a pulse' # do we need this with our existing asound.conf?

- name: vdr-config | use vaapi for softhddevice if we got an intel IGP
  lineinfile:
    path: /etc/vdr/conf.avail/softhddevice.conf
    line: '-v va-api'
    state: '{{ "present" if (not nvidia_detected and intel_detected) else "absent" }}'

- name: add a login shell for the user vdr
  user:
      name: '{{ vdr.user }}'
      shell: '/bin/bash'
      state: present
      uid: '{{ vdr.uid }}'
      groups: '{{ vdr.group }}'
      append: yes

- name: apt | install packages for xorg
  apt:
    name:
      - yavdr-xorg
      - python3-dbus2vdr
      - python3-yavdrfrontend
      - tmux
      - vdr-plugin-desktop
      - vdr-plugin-osd2web
      - feh
    state: present

- name: apt | install packages for Intel IGP
  apt:
    name:
      - i965-va-driver-shaders
    state: present
  when: intel_detected | bool and not nvidia_detected | bool

- name: Install yaVDR Media (e.g. Backgrounds)
  apt:
    name: yavdr-media

- name: command | write keyboard configuration to /etc/X11/xorg.conf.d/00-keyboard.conf
  command: write-x11-keyboard-config
  args:
    creates: /etc/X11/xorg.conf.d/00-keyboard.conf
  # NOTE: write-x11-keyboard-config is in the xlogin package
  # Ubuntu's systemd is patched, so it does not create the file automatically

- name: add snippet to ignore eventlircd devices in xorg
  template:
    src: templates/xorg-ignore-eventlircd.conf.j2
    dest: /etc/X11/xorg.conf.d/40-ignore-eventlircd.conf

- name: apt | install desktop programs
  apt:
    name:
      - xterm
      - firefox
      - kiosk-browser
    state: present
