---
# file: roles/yavdr-xorg/tasks/setup-xorg.yml
- name: create directories for systemd drop-in files
  file:
    dest: '{{ item }}'
    state: directory
  loop:
    - "/etc/systemd/system/x@.service.d/"
    - "/etc/systemd/system/vdr.service.d/"
    - "/etc/systemd/system/user@{{ vdr.uid }}.service.d/"
    - "/etc/X11/xorg.conf.d/"

- name: systemd-drop-in | add dependency to X-server for vdr.service
  template:
    src: templates/vdr-xorg.conf
    dest: /etc/systemd/system/vdr.service.d/vdr-xorg.conf
  notify: ["Reload Units"]

- name: systemd-drop-in | start x@.service after plymouth.service
  template:
    src: templates/x@service.d/plymouth.conf.j2
    dest: /etc/systemd/system/x@.service.d/plymouth.conf
  notify: ["Reload Units"]

- name: systemd-drop-in | start x@.service before xlogin@.service
  template:
    src: templates/x@service.d/xlogin.conf.j2
    dest: /etc/systemd/system/x@.service.d/xlogin.conf
  notify: ["Reload Units"]

- name: systemd-drop-in | load environment file for vdr.service
  template:
    src: templates/systemd/vdr-environ.j2
    dest: /etc/systemd/system/vdr.service.d/load-environ.conf
  notify: ["Reload Units"]

- name: systemd-drop-in | user@{{ vdr.uid }}.service depends on x@vt7.service
  template:
    src: templates/user@666.service.d/x-dependency.conf.j2
    dest: '/etc/systemd/system/user@{{ vdr.uid }}.service.d/x-dependency.conf'
  notify: ["Reload Units"]

- name: vdr-config | create softhddevice.conf if it doesn't exist yet
  lineinfile:
    path: /etc/vdr/conf.avail/softhddevice.conf
    create: yes
    state: present
    line: '[softhddevice]'

- name: vdr-config | start softhddevice detached and set audio to pulseaudio
  lineinfile:
    path: /etc/vdr/conf.avail/softhddevice.conf
    line: '{{ item }}'
  loop:
      - '-D'
      - '-w alsa-driver-broken'
      - '{{ "-v va-api" if (intel_detected and not nvidia_detected) else "" }}'
      # - '-a pulse' # do we need this with our existing asound.conf?

- name: add a login shell for the user vdr
  user:
      name: '{{ vdr.user }}'
      shell: '/bin/bash'
      state: present
      uid: '{{ vdr.uid }}'
      groups: '{{ vdr.group }}'
      append: yes

- name: apt | install packages for xorg
  apt:
    name:
      - yavdr-xorg
      - edid-decode
      - python3-dbus2vdr
      - python3-yavdrfrontend
      - tmux
      - vdr-plugin-desktop
      - feh
    state: present

- name: apt | install packages for Intel IGP
  apt:
    name:
      - i965-va-driver-shaders
      - intel-media-va-driver-non-free
    state: present
  when: intel_detected | bool and not nvidia_detected | bool

- name: add ppa:oibaf/graphics-drivers for up to date mesa drivers
  apt_repository:
    repo: ppa:oibaf/graphics-drivers
  when: amd_detected | bool and not nvidia_detected | bool
  register: oibaf_ppa

- name: update package lists and all packages after adding ppa:oibaf/graphics-drivers
  apt:
    upgrade: dist
    update_cache: yes
  when: oibaf_ppa.changed

- name: apt | install packages for AMD GPUs
  apt:
    name:
      - mesa-vdpau-drivers
      - mesa-va-drivers
    state: present
  when: amd_detected | bool and not nvidia_detected | bool

- name: Install yaVDR Media (e.g. Backgrounds)
  apt:
    name: yavdr-media

- name: command | write keyboard configuration to /etc/X11/xorg.conf.d/00-keyboard.conf
  command: write-x11-keyboard-config
  args:
    creates: /etc/X11/xorg.conf.d/00-keyboard.conf
  # NOTE: write-x11-keyboard-config is in the xlogin package
  # Ubuntu's systemd is patched, so it does not create the file automatically

- name: add snippet to ignore eventlircd devices in xorg
  template:
    src: templates/xorg-ignore-eventlircd.conf.j2
    dest: /etc/X11/xorg.conf.d/40-ignore-eventlircd.conf

- name: apt | install desktop programs
  apt:
    name:
      - xterm
      - firefox
      - kiosk-browser
    state: present
