# vars file for wakeup role

# name of add-on package(s) to install (it can be made a list of packages)
wakeup_addon_packages:
  acpiwakeup: vdr-addon-acpiwakeup
  stm32wakeup: vdr-addon-stm32irmp-wakeup

# path to configuration file, corresponding template is called like the
# file's basename with .j2
wakeup_addon_confs:
  acpiwakeup: /etc/vdr/vdr-addon-acpiwakeup.conf
  stm32wakeup: /etc/vdr/vdr-addon-stm32irmp-wakeup.conf
